apiVersion: batch/v1
kind: Job
metadata:
  name: bidding-migration-job
spec:
  template:
    spec:
      containers:
      - name: migration
        image: bidding-app:latest
        imagePullPolicy: IfNotPresent
        command: 
          - "sh"
          - "-c"
          - "python manage.py migrate --noinput && echo 'Migrations completed successfully' && exit 0"
        envFrom:
        - configMapRef:
            name: bidding-config   
        - secretRef:
            name: bidding-secrets  
      restartPolicy: OnFailure