# Generated by Django 6.0 on 2026-01-03 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="bidhistory",
            options={"ordering": ["-price"], "verbose_name_plural": "Bid Histories"},
        ),
        migrations.AddField(
            model_name="bidhistory",
            name="bidder_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
