# Generated by Django 6.0 on 2026-01-03 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0002_alter_bid_options_alter_bidhistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidhistory",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
