# Generated by Django 6.0 on 2026-01-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0003_bidhistory_added_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=50,
            ),
        ),
    ]
